### ISSUE TITLE
Add optional description field per setting

### ISSUE THREAD

**Issue by bumbus** [arillo/silverstripe-arbitrarysettings#3]
```
settings:
    show_title:
      options:
        0: "No"
        1: "Yes"
      default: 0
      label: "Show title as image caption?"
      description: "The caption will not be displayed."
```
